### PR TITLE
modify view_page

### PR DESCRIPTION
**Pull request by gyu1039**

### CODE REVIEW

**Review by Ljh3141 — APPROVED** [review]

**Review by ghk4889 — APPROVED** [review]

**Comment by gyu1039** [comment]
+ base_form  페이지 수정 코드

93번째 줄 -> <div th:replace="~{|${department}/fragment_ojh| :: subSidebar}"></div>

**Comment by gyu1039** [comment]
<div th:replace="~{|${department}/fragment_ojh| :: subSidebar}"></div>

**Comment by gyu1039** [comment]
<div th:replace="~{|${department}/fragment_ojh| :: subSidebar}"></div>

**Comment by gyu1039** [comment]
`<div th:replace="~{|${department}/fragment_ojh| :: subSidebar}"></div>`

**Pull request merged**
